# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d03a8dc2fadf11261aba676e501bd80b00f63c11391e7c2983e7f1f49bd4f96d11921d8ea209e4a690a49088ad0da2b92033e9285eef9015cf85670d8bb6d87

test:
  secret_key_base: 39b27c78bfd30df7c67766cc10178f8d3d1d65090824b1fac5f3ba5356f1a26d5fa955092af058ce36e0273c51518e67c3bf06fe7473eff3c2458fe8f77369e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
